packages:
  - apps/*
  - packages/*
overrides:
  eslint: ^9.30.1
catalogs:
  dev:
    '@esbuild-plugins/node-globals-polyfill': ^0.2.3
    '@eslint/eslintrc': ^3
    '@eslint/js': ^9.25.0
    '@next/third-parties': 15.3.5
    '@tailwindcss/postcss': ^4
    '@tailwindcss/vite': ^4.1.7
    '@types/node': ^20
    '@types/react': ^19
    '@types/react-dom': ^19
    '@vitejs/plugin-react': ^4.4.1
    eslint: ^9.30.1
    eslint-config-next: 15.3.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.19
    globals: ^16.0.0
    input-otp: ^1.4.2
    size-limit: 11.1.6
    tailwindcss: ^4
    tw-animate-css: ^1.2.8
    typescript: ^5.8.3
    typescript-eslint: ^8.30.1
    ts-patch: ^3.3.0
    tslib: 2.8.1
    turbo: ^2.5.3
    tsup: 8.5.0
    vite: ^6.3.5
    vite-plugin-html: ^3.2.2
    vite-plugin-singlefile: ^2.2.0
    worker-loader: ^3.0.8
  peer:
    eslint: ^9.30.1
  prod:
    '@next/third-parties': 15.3.5
    '@noble/ciphers': ^1.3.0
    '@noble/curves': ^1.9.1
    '@noble/hashes': ^1.8.0
    '@radix-ui/react-dialog': ^1.1.11
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-hover-card': ^1.1.11
    '@radix-ui/react-label': ^2.1.4
    '@radix-ui/react-popover': ^1.1.11
    '@radix-ui/react-progress': ^1.1.7
    '@radix-ui/react-radio-group': ^1.3.7
    '@radix-ui/react-scroll-area': ^1.2.6
    '@radix-ui/react-select': ^2.2.2
    '@radix-ui/react-separator': ^1.1.4
    '@radix-ui/react-slider': ^1.3.2
    '@radix-ui/react-slot': ^1.2.0
    '@radix-ui/react-switch': ^1.2.5
    '@radix-ui/react-tabs': ^1.1.11
    '@radix-ui/react-tooltip': ^1.2.7
    '@scure/base': ^1.2.5
    '@scure/bip32': ^1.7.0
    '@scure/bip39': ^1.6.0
    buffer: ^6.0.3
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    eciesjs: ^0.4.15
    input-otp: ^1.4.2
    lucide-react: ^0.503.0
    next: 15.3.5
    next-intl: ^4.3.4
    next-themes: ^0.4.6
    ogl: ^1.0.11
    postcss: ^8.5.3
    react: ^19.0.0
    react-dom: ^19.0.0
    react-router-dom: ^7.6.0
    react-use-dark-mode: ^2.0.3
    sonner: ^2.0.3
    tailwind-merge: ^3.2.0
